services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    networks:
      - framework-network
    depends_on:
      - redis
      - db
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app/:/var/www/html/
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - framework-network
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: framework_db
      MYSQL_USER: framework_user
      MYSQL_PASSWORD: framework_PASSWORD1
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - framework-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - framework-network

networks:
  framework-network:
    external: true